version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${TAG_NAME}-repo-spring3-javapp
      - echo $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - sed -i "s/TAGNAME/${TAG_NAME}/g" cloudformation.yaml
      - sed -i "s@IMAGE_TAG@${IMAGE_TAG}@g" cloudformation.yaml
      - sed -i "s@ECR_REPO@${ECR_REPO}@g" cloudformation.yaml
      - sed -i "s@ECS_CPU@${CPU}@g" cloudformation.yaml
      - sed -i "s@ECS_MEMORY@${MEMORY}@g" cloudformation.yaml
      - sed -i "s@MIN_TASK@${MIN_TASK}@g" cloudformation.yaml
      - sed -i "s@MAX_TASK@${MAX_TASK}@g" cloudformation.yaml
artifacts:
  files:
    - cloudformation.yaml